name: Covid19 Tracker CI Workflow
on:
  push:
    branches:
      - master
      - dev
      - config-detekt
  pull_request:
    branches:
      - master
      - dev

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  test:
    name: Build and run tests
    runs-on: macos-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Detekt
        run: ./gradlew detekt
