name: Covid19 Tracker CI Workflow
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  test:
    name: Build and run tests
    runs-on: macos-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest --stacktrace

      - name: Run instrumentation & ui tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          profile: Nexus 6
          emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -camera-back none
          script: ./gradlew connectedAndroidTest --stacktrace

      - name: Upload reports
        uses: actions/upload-artifact@v1
        with:
          name: Covid19 Tracker - Tests reports
          path: app/build/reports

      - name: Generate apk
        run: ./gradlew assembleDebug --stacktrace

      - name: Upload apk
        uses: actions/upload-artifact@v1
        with:
          name: Covid19 Tracker - Apk debug
          path: app/build/outputs/apk/debug/covid19tracker-debug.apk