name: Covid19 Tracker CI Workflow
on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

env:
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"

jobs:
  test:
    name: Build and run tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Detekt code analysis
        uses: natiginfo/action-detekt-all@1.15.0-RC1
        with:
          args: --fail-fast --config detekt.yml

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest --stacktrace

      #- name: Run instrumentation tests
        #uses: reactivecircus/android-emulator-runner@v2
        #with:
          #api-level: 29
          #arch: x86
          #profile: Nexus 6
          #avd-name: test
          #emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -camera-back none
          #disable-animations: true
          #script: ./gradlew connectedCheck --stacktrace

      - name: Upload Reports
        uses: actions/upload-artifact@v1
        with:
          name: Covid19 Tracker - Tests reports
          path: app/build/reports
        
  #generate-apk:
    #name: Generate apk
    #runs-on: ubuntu-latest
    #needs:
      #- test
    #steps:
      #- name: Checkout
        #uses: actions/checkout@v2

      #- name: Setup JDK 1.8
        #uses: actions/setup-java@v1
        #with:
          #java-version: 1.8

      #- name: Generate apk
      # run: ./gradlew assembleDebug --stacktrace

      #- name: Upload APK
      #  uses: actions/upload-artifact@v1
      #  with:
      #    name: Covid19 Tracker - APK Debug
      #    path: /app/build/outputs/apk/debug/covid19tracker-debug.apk
